spring:
  application:
    name: backend
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5433}/${DB_NAME:receptfeed}
    username: ${DB_USERNAME:receptfeed}
    password: ${DB_PASSWORD:receptfeed}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  flyway:
    enabled: true
